name: Metrics

on:
  schedule:
    - cron: "0 */3 * * *"          # every 3 hours
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    concurrency:
      group: metrics-update
      cancel-in-progress: true

    steps:
      # 1 · Checkout using your PAT so the push is attributed to you
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.METRICS_TOKEN }}

      # 2 · Cache Metrics dependencies
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/lockfiles') }}

      # 3 · Run Metrics without auto-committing
      - name: Generate GitHub Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: none
          user: bslatyer
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Australia/Sydney
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_traffic: yes
          plugin_wakatime: no

      # 4 · Copy rendered file(s) into the repo
      - name: Move freshly rendered files
        run: |
          cp -f /metrics_renders/* ./ || true

      # 5 · Configure SSH signing
      - name: Configure SSH signing
        env:
          SSH_SIGNING_KEY: ${{ secrets.SSH_SIGNING_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_SIGNING_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          git config --global user.name  "Braeden Slatyer"
          git config --global user.email "braeden@slats.io"
          git config --global gpg.format ssh
          git config --global user.signingkey ~/.ssh/id_ed25519
          git config --global commit.gpgsign true
          git config --global gpg.ssh.program /usr/bin/ssh-keygen

      # 6 · Commit & push (SSH-signed) only if something changed
      - name: Commit & push (signed)
        run: |
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: Update GitHub Metrics [skip ci]"
            git push
          else
            echo "No changes – nothing to commit."
          fi